const SET_CURRENT_USER = `SET_CURRENT_USER`;
const SET_USER_AUTH = `SET_USER_AUTH`;
const SET_OTP_TYPE = "SET_OTP_TYPE";
const SET_USER_ROLE = "SET_USER_ROLE";
const SET_ACCOUNT_ID = "SET_ACCOUNT_ID";
const SET_OTP = "SET_OTP";
const SET_ACCOUNT_HOLDER = "SET_ACCOUNT_HOLDER";
const SET_INVESTMENT_CUSTOMER = "SET_INVESTMENT_CUSTOMER";
const SET_WHOAMI = "SET_WHOAMI"; 
const SET_ROUTE = "SET_ROUTE";
const CLEAR_SESSION = "CLEAR_SESSION";
const SET_SEARCH = "SET_SEARCH";
const FETCH_CUSTOMER = "FETCH_CUSTOMER";
const FETCH_TRANSACTION = "FETCH_TRANSACTION";
const SET_USER_REGION = "SET_USER_REGION";
const SET_USER_ACCOUNT = "SET_USER_ACCOUNT";
const SET_GLOBAL_DATA = "SET_GLOBAL_DATA";
const SET_INVOICE_DATA = "SET_INVOICE_DATA";

export {
    SET_CURRENT_USER,
    SET_USER_AUTH,
    SET_OTP_TYPE,
    SET_USER_ROLE,
    SET_ACCOUNT_ID,
    SET_OTP,
    SET_ACCOUNT_HOLDER,
    SET_INVESTMENT_CUSTOMER,
    SET_WHOAMI,
    SET_ROUTE,
    CLEAR_SESSION,
    SET_SEARCH,
    FETCH_CUSTOMER,
    FETCH_TRANSACTION,
    SET_USER_REGION,
    SET_USER_ACCOUNT,
    SET_GLOBAL_DATA,
    SET_INVOICE_DATA
}